okta:
  oauth2:
    issuer: ${OKTA_SERVER}
    client-id: ${OKTA_CLIENT_ID}

app:
  http:
    cors:
      allowedOrigins: ${CORS_ALLOWED_ORIGINS}
    security:
      deny-by-default: false
  client:
    users:
      url: ${USERS_API_URL}
